### ISSUE TITLE
Plans for maxscale 2?

### ISSUE THREAD

**Issue by hoffoo** [skord/maxscale_exporter#5] opened 2019-05-24 18:49 UTC
Are there plans to support maxscale 2+

Thanks!

**Comment by manucho6** [comment] 2019-05-27 20:05
maxscale version 2.3.x  is the problem.

**Comment by RubenHoms** [comment] 2019-05-28 14:40
Yep, I'd love to help out to support version `>2.3.x`. I found out in #4 what the issue is and how we could potentially fix it. I don't have time right now to work on the solution myself but I'm more than willing to help out where needed on a PR.
Closing this because it's a duplicate of #4

**Closed as completed by RubenHoms** 2019-05-28 14:40 UTC
